apiVersion: v1
kind: Pod
metadata:
  name: imageerrorpod
spec:
  containers:
  - name: imageerrorcontainer
    image: enignx


//image ismi yanlış olduğu için oluşan pod ImagePullBackOff stage ne geçer. belirli aralıkalrla tekrar çekmeye çalşr    