apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


// app:backend ile şunu dyrz tarfiği bu labele sahip olan podlara yönldnr     