apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldeployment
  labels:
    team: development
spec:
  replicas: 10
  selector:
    matchLabels:
      app: rolling
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: rolling
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80


//type:RollingUpdate deployment da değişiklk yaptığımda eskileri kademeli sil ve yenileri olştr
//maxUnavailable:2 en fazla 2 podu sil, deploymentta değişiklk yapıldığında
//maxSurge:2 geçiş sırasında en fazla eski pod sayısı